# -*- coding:utf-8 -*-
from jinstall.configs.base import *


install_configs['path.package.remote'] = '/home/download'
install_configs['git.user.name'] = 'jiangwei'
install_configs['git.user.email'] = 'jiangwei07061625@163.com'
install_configs['redis.port'] = '6688'
install_configs['redis.path.install'] = '/usr/local/redis'
install_configs['redis.path.log'] = '/home/logs/redis'
install_configs['redis.insight.host'] = '192.168.96.21'
install_configs['redis.insight.port'] = '8001'
install_configs['redis.insight.path.install'] = '/usr/local/redis_insight'
install_configs['redis.insight.path.log'] = '/home/logs/redis_insight'
install_configs['memcached.path.install'] = '/usr/local/memcached'
install_configs['libmemcached.path.install'] = '/usr/local/libmemcached'
install_configs['mongodb.port'] = '27017'
install_configs['mongodb.path.install'] = '/usr/local/mongodb'
install_configs['cassandra.path.install'] = '/usr/local/cassandra'
install_configs['cassandra.path.log'] = '/home/logs/cassandra'
install_configs['goinception.path.install'] = '/usr/local/goinception'
install_configs['goinception.path.log'] = '/home/logs/goinception'
install_configs['node.path.log'] = '/home/logs/nodejs'
install_configs['node.forever.path.log'] = '/home/logs/nodeforever'
install_configs['etcd.path.install'] = '/usr/local/etcd'
install_configs['lua.path.install'] = '/usr/local/openresty/luajit'
install_configs['luarocks.path.install'] = '/usr/local/luarocks'
install_configs['librabbitmq.path.install'] = '/usr/local/librabbitmq'
install_configs['rabbitmq.path.install'] = '/usr/local/rabbitmq'
install_configs['openresty.path.log'] = '/home/logs/nginx'
install_configs['openresty.path.configs'] = '/home/configs/nginx'
install_configs['kong.path.install'] = '/usr/local/kong'
install_configs['kong.path.log'] = '/home/logs/kong'
install_configs['php7.path.install'] = '/usr/local/php7'
install_configs['php7.screw.tool'] = '0'
install_configs['python3.path.install'] = '/usr/local/python3'
install_configs['paddlehub.path.install'] = '/usr/local/paddlehub'
install_configs['paddlehub.path.log'] = '/home/logs/paddlehub'
install_configs['gitea.path.install'] = '/usr/local/gitea'
