#!/bin/sh
# chkconfig: 2345 10 90 
# description: Start and Stop redis

PASSWARD=yjbn15su
EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli

PIDFILE=/var/run/redis_${REDISPORT}.pid
CONF="/etc/redis/${REDISPORT}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]; then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting Redis server..."
            $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]; then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping ..."
            $CLIEXEC -p $REDISPORT -a $PASSWARD shutdown
            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis to shutdown ..."
                sleep 1
            done
            rm -f $PIDFILE
            echo "Redis stopped"
        fi
        ;;
    restart)
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE)
            $CLIEXEC -p $REDISPORT -a $PASSWARD shutdown
            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis to shutdown ..."
                sleep 1
            done
            rm -f $PIDFILE
            echo "Redis stopped"
        fi
        echo "Starting Redis server..."
        $EXEC $CONF
        ;;
    *)
        echo "Please use start or stop or restart as first argument"
        ;;
esac
