# 不与Vi兼容
set nocompatible
# 显示行号
set number
# 显示光标所在的当前行的行号
set relativenumber
# 光标所在的当前行高亮
set cursorline
set textwidth=80
set nowrap
set scrolloff=5
set sidescrolloff=15
set laststatus=2
set ruler
# 打开语法高亮
syntax on
# 在底部显示当前处于命令模式还是插入模式
set showmode
# 命令模式下在底部显示当前键入的指令
set showcmd
# 支持鼠标拖拽复制
set mouse=r
# 使用utf-8编码
set encoding=utf-8
# 启用256色
set t_Co=256
# 开启文件类型检查,并且载入与该类型对应的缩进规则
filetype indent on
# 将输入的tab展开成空格
set expandtab
# 设置一个tab所占的空格长度为4
set tabstop=4
# 设置程序自动缩进时所占的空格长度,最好设置为与tabstop相同
set shiftwidth=4
# 在开启expantab后,需要设置使用退格键时删除的空格数
set softtabstop=4
# 按下回车键后下一行的缩进会自动跟上一行的缩进保持一致
set autoindent
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set spell spelllang=en_us
set nobackup
set noswapfile
set undofile
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swp//
set undodir=~/.vim/.undo//
set autochdir
set noerrorbells
set visualbell
set history=1000
set autoread
set listchars=tab:»■,trail:■
set list
set wildmenu
set wildmode=longest:list,full
