bolt-path: /usr/local/influxdb/influxd.bolt
engine-path: /usr/local/influxdb/engine
sqlite-path: /usr/local/influxdb/influxd.sqlite
e2e-testing: true
flux-log-enabled: true
http-bind-address: ":18086"
http-idle-timeout: 3m0s
http-read-header-timeout: 10s
http-read-timeout: 30s
http-write-timeout: 30s
influxql-max-select-buckets: 0
influxql-max-select-point: 0
influxql-max-select-series: 0
log-level: info
metrics-disabled: false
nats-max-payload-bytes: 2097152
nats-port: -1
no-tasks: false
pprof-disabled: false
query-concurrency: 30
query-initial-memory-bytes: 10485760
query-max-memory-bytes: 314572800
query-memory-bytes: 10485760
query-queue-size: 15
reporting-disabled: true
secret-store: vault
session-length: 120
ui-disabled: false
vault-token: ex3en-t0ken-958a-f490-c7fd0eda5e9e
