global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 20s
  group_interval: 3m
  repeat_interval: 1h
  receiver: 'dingtalk_yxp1'
  routes:
  - receiver: dingtalk_yxp1
    group_wait: 15s
    match_re:
      alertname: '实例存活告警|服务存活告警'
  - receiver: dingtalk_yxp2
    group_wait: 15s
    match_re:
      alertname: '内存使用告警|磁盘使用告警'
receivers:
- name: 'dingtalk_yxp1'
  webhook_configs:
  - url: 'http://172.18.134.141:18090/dingtalk/yxp1/send'
    send_resolved: true
- name: 'dingtalk_yxp2'
  webhook_configs:
    - url: 'http://172.18.134.141:18090/dingtalk/yxp2/send'
      send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
