global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.3.168:18091
rule_files:
  - "first_rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    file_sd_configs:
    - refresh_interval: 1440m
      files:
        - "/usr/local/prometheus/conf/prom.yml"
  - job_name: 'pushgateway'
    honor_labels: true
    file_sd_configs:
      - refresh_interval: 1440m
        files:
          - "/usr/local/prometheus/conf/pushgateway.yml"
#remote_read:
#  - url: "http://192.168.3.168:18086/api/v2/query?org=jw01"
#    read_recent: true
remote_write:
  - url: "http://192.168.3.168:18087/receive"
