# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.3.168:19092

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    file_sd_configs:
    - refresh_interval: 1440m
      files:
        - "/usr/local/prometheus/conf/prometheus.yml"
  - job_name: 'pushgateway'
    honor_labels: true
    file_sd_configs:
      - refresh_interval: 1440m
        files:
          - "/usr/local/prometheus/conf/pushgateway.yml"
  - job_name: 'netdata'
    metrics_path: /api/v1/allmetrics?format=prometheus
    file_sd_configs:
      - refresh_interval: 1440m
        files:
          - "/usr/local/prometheus/conf/netdata.yml"
  - job_name: 'mongodb'
    file_sd_configs:
      - refresh_interval: 1440m
        files:
          - "/usr/local/prometheus/conf/mongodb.yml"
  - job_name: 'node'
    file_sd_configs:
      - refresh_interval: 1440m
        files:
          - "/usr/local/prometheus/conf/node.yml"
  - job_name: 'mysql'
    file_sd_configs:
      - refresh_interval: 1440m
        files:
          - "/usr/local/prometheus/conf/mysql.yml"
  - job_name: 'redis'
    file_sd_configs:
      - refresh_interval: 1440m
        files:
          - "/usr/local/prometheus/conf/redis.yml"
  - job_name: 'nginx-vts'
    file_sd_configs:
      - refresh_interval: 1440m
        files:
          - "/usr/local/prometheus/conf/nginx-vts.yml"
